project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Chris Edwards"
  google-analytics: "G-69T2DQZDC7"
  site-url: "https://edwchris.github.io"
  description: "Sonography"

  page-footer:
    left: "&copy; Copyright 2024, Chris Edwards"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    right:
        
      - href: blog/index.qmd
        text: Blog

      - href: projects/index.qmd
        text: Projects

      - href: about/index.qmd
        text: About
      
      - icon: rss
        href: blog/index.xml
        
      - icon: github
        href: https://github.com/edwchris

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false



