project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Chris Edwards"

  page-footer:
    left: "&copy; Copyright 2024, Chris Edwards"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects/index.qmd
        text: Projects

      - href: about/index.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



