---
title: "Plot2"
editor: visual
draft: true
---

```{r}
rm(list = ls())
gc()
```

```{r}
#| warning: false
# load libraries -------

rm(list = ls())
gc()

library(data.table)
library(ggplot2)
library(stringr)
library(ggtext)
library(extrafont)
library(paletteer)
library(tidyverse)
```

```{r}
# load data --------

df <- fread("data/data_comb3.csv")
```

```{r}
pace <- df%>%
  mutate(
    pace_category = cut(
      pace_sec_per_km,
      breaks = c(-Inf, 240, 260, 300, 330, Inf),
      labels = c(
        "<4:00 min/km",
        "4:00–4:20 min/km",
        "4:20–5:00 min/km",
        "5:00–5:30 min/km",
        ">5:30 min/km"
      ),
      right = FALSE
    )
  ) %>%
  group_by(Month,pace_category) %>%
  summarise(
    Total_Distance_km = sum(Distance, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  group_by(Month) %>%
  mutate(
    Percentage_Distance = round(100 * Total_Distance_km / sum(Total_Distance_km), 1)
  ) %>%
  ungroup()


pace


```

```{r}

# Cleaning -------------

pace$Month <- factor(pace$Month, levels = c("January", "February", "March","April", "May", "Jun"))

pace

# colours-----------


col = c("#00429d", "#73a2c6", '#396375', '#5a8192', '#6f6e9a', '#a2a0cf', '#e37b78',"#A65628", '#b24745')


grid_colors <- c(
  ">5:30 min/km"       = "#d0d0d0",  # very low intensity
  "5:00–5:30 min/km"   = "#a6bddb",  # low intensity
  "4:20–5:00 min/km"   = "#fdbb84",  # undesirable pace
  "4:00–4:20 min/km"   = "#2b8cbe",  # ideal marathon pace
  "<4:00 min/km"       = "#bd0026"   # high intensity
)

grid_colors <- c(
  ">5:30 min/km"       = "#5a8192",  # very low intensity
  "5:00–5:30 min/km"   = "#c1cbe3",  # low intensity
  "4:20–5:00 min/km"   = "#a4a0d1",  # caution / inefficiency
  "4:00–4:20 min/km"   = "#8570b0",  # ideal marathon pace
  "<4:00 min/km"       = "#67206f"   # high intensity
)



```

```{r}
p <-  ggplot(pace, aes(x = Month, y = Percentage_Distance, fill = pace_category)) +

    geom_bar(stat = "identity", width = 0.5) +
   scale_fill_manual(values = grid_colors) +

    labs(
        title = "Monthly % Distribution of Kilometres by Pace Zone",
        subtitle = "4:00-4:20 min/km represents target Marathon Pace (MP).",
        caption = " Source: <b> Garmin Connect</b> | Graphic: <b>Chris Edwards</b>",
        y = "Distance Run (km)", 
        fill = "Type"
    ) +
    
    theme_minimal(base_family = "Candara") +
    
    theme(
        
        axis.title.x = element_blank(),
        
        axis.title.y = element_text(size = 9),
        
        axis.text.x = element_text(size = 7),
        axis.text.y = element_text(size = 7),
        
        legend.text = element_text(size = 7),         # Smaller text
        legend.title = element_text(size = 8),        # Optional: smaller title
        legend.key.size = unit(0.8, "lines"),         # Smaller boxes
        legend.spacing.y = unit(0.5, "lines"),
        
        legend.position = "right",
        # legend.title = element_text(size = 8),
        # legend.text = element_text(size = 7),
        
        panel.grid.major = element_line(color = "grey75", linetype = "dashed", lineend = "round"),
        panel.grid.minor = element_blank(),
        
        plot.title = element_markdown(size = 14, face = "bold", hjust = 0.5, margin = margin(t = 2, b = 2)),
        plot.subtitle = element_markdown(size = 10, hjust = 0.5,  color = "grey30", margin = margin(t = 5, b = 10)),
        plot.caption  = element_markdown(margin = margin(t = 25), size = 6, hjust = 1.28),
        
        
        plot.margin = margin(20, 20, 20, 20),
        
        plot.background = element_rect(fill = "#e4e4e3", color = NA) 
    )  +  
        coord_flip()  
        
    
p



ggsave(
    plot = p, filename = "Rplot.png",
    width = 8, height = 6, units = "in", dpi = 600
)    
```

```{r}
# load libraries -------

library(data.table)
library(ggplot2)
library(stringr)
library(ggtext)
library(extrafont)
library(paletteer)
library(tidyverse)
```

```{r}
# load data --------

df <- fread("data/data_comb3.csv")
```

```{r}
# clean data -----

# Filter dataset between 245 sec (4:05) and 255 sec (4:15) per kilometer

df_pace <- df %>%
  filter(pace_sec_per_km >= 245, pace_sec_per_km <= 255)

# very few kms in Jan, Feb and March let's filter out these as well and lets only include complete laps i.e. laps =>

df_pace <- df_pace %>% filter((Month == "April" | Month == "May" | Month == "Jun") & Distance >= 1)

df_pace$Month <- factor(df_pace$Month, levels = c("April", "May", "Jun"))
```

```{r}
# outliers 

colors = paletteer_c("ggthemes::Sunset-Sunrise Diverging", 9)
```

```{r}

gr <- ggplot() +
  geom_boxplot(
    data=df_pace,
    aes(x=Month, y = `Avg HR`, fill = Month ),
    position = position_dodge(width = 0.5),
    width = .35, outlier.shape = NA, alpha = 0.45, linewidth = 0.2
  ) +
  
  geom_point(
    data = df_pace,
    aes(x= Month, y= `Avg HR`, fill = Month),
    position = position_jitterdodge(jitter.width = .25, dodge.width = .5),
    shape = 21, size = 2.5, stroke = .15, color="white"
  ) +
  
    scale_fill_manual(values = colors) +
    
    scale_color_manual(values = colors) +
  
      labs(
        title = "Average HR at approximate Marathon Pace",
        subtitle = "Distribution of Average HR values for laps recorded at 4:05 - 4:15 min/km. ",
        caption = "Source: <b>Garmin Connect</b> | Graphic: <b>Chris Edwards</b>",
        x = "Month",
        y = "Average Heart Rate (bpm)"
    ) +
    
    theme_minimal() +
      theme(
        legend.position = "none",
        
        axis.title.x = element_text(size = 10, family = "Candara"),
        axis.title.y = element_text(size = 10, family = "Candara"),
        axis.text.x = element_text(size = 10, family = "Candara"),
        axis.text.y = element_text(size = 10, family = "Candara"),
        
        panel.grid.major = element_line(linewidth = .35, color = "grey80", linetype = "dashed"),
        panel.grid.minor = element_line(linewidth = .35, color = "grey80", linetype = "dashed"),
        
        plot.title = element_markdown(size = 16, face = "bold", hjust = 0.5, family = "Candara", margin = margin(t = 15, b = 5)),
        plot.subtitle = element_markdown(size = 11, hjust = 0.5, family = "Candara", color = "grey30", margin = margin(t = 5, b = 25)),
        plot.caption = element_markdown(margin = margin(t = 20), size = 8, family = "Candara", hjust = 1),
        
        plot.margin = margin(20, 20, 20, 20),
        
        plot.background = element_rect(fill = "#e4e4e3", color = NA)
    )

gr

```
